language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

before_install:
    - composer self-update

install:
    - composer install --prefer-dist --no-progress

before_script:
    - pecl install intl
    - echo "extension=intl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

after_script:
    - bin/coveralls
